name: Weekly Python Auto-Commit

on:
  push:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow
  
  
jobs:
  run-python-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2' 

      - name: Inject Secrets
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
      
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: |
          python GithubStatsTracker.py

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add .
          git commit -m "Weekly update from GitHub Actions $(date '+%Y-%m-%d')" || echo "No changes"
          git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git HEAD:main

