name: Weekly Python Auto-Commit

on:
  schedule:
    - cron: '0 0 * * 0'  # Every Sunday at midnight
  workflow_dispatch:  # Allows manual triggering of the workflow
  
  
jobs:
  run-python-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Specify the Python version you want to use

      - name: Inject Secrets
        run: |
          echo "USER_NAME=${{ secrets.USER_NAME }}" >> .env
          echo "ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}" >> .env
      
      - name: Run Python script
        run: |
          pip install python-dotenv
          python GithubStatsTracker.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Weekly update from GitHub Actions" || echo "No changes to commit"
          git push